# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_delete', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Atype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'a_type',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='atype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Atype'),
        ),
    ]
