# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181207_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atype',
        ),
    ]
